services:
  backend:
    build:
      context: ./services/backend
    container_name: meshgate-backend
    ports:
      - "8001:5000"

  frontend:
    build:
      context: ./services/frontend
    container_name: meshgate-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend